### ISSUE TITLE
除了【首页】成功汉化，后面的部分都没成功。

### ISSUE THREAD

**Issue by Yesr00** [xiaoxuan6/laravel-admin-breadcrumb#1]
如题。只有首页这两个字成功汉化了。后面其他的部分都没成功，比如edit汉化后应该是编辑，但是并没有显示为编辑，还是显示的edit.

然后关于

将控制器中
use Encore\Admin\Controllers\AdminController;
替换
use James\Admin\Breadcrumb\BaseController;

现有的控制器中没有use Encore\Admin\Controllers\AdminController;

**Comment by Yesr00** [comment]
![image](https://user-images.githubusercontent.com/47804568/66697227-4a153000-ed06-11e9-95ec-d2026cb44d07.png)

**Comment by Yesr00** [comment]
求大佬指导

**Comment by xiaoxuan6** [comment]
![图片](https://user-images.githubusercontent.com/32762220/66986662-e3bb5380-f0f1-11e9-9ace-121674e1bfd1.png)
框架自带的改不了，只能修改你自己新创建的控制器

**Comment by Yesr00** [comment]
use James\Admin\Breadcrumb\BaseController;  大佬。改这个的话。需要把extend也改成 BaseController么？
![image](https://user-images.githubusercontent.com/47804568/66988449-1d418e00-f0f5-11e9-896d-3f9d5b045341.png)
这个自建模块也是没被汉化。
